# Generated by Django 2.2.5 on 2019-11-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codearena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='question_text',
        ),
    ]
