# Generated by Django 2.2.5 on 2019-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codearena', '0002_remove_event_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_valid',
            field=models.DateTimeField(verbose_name='validity date'),
        ),
    ]
